services:
  cockroach:
    image: cockroachdb/cockroach:v23.1.6
    restart: always
    ports:
      - 36257:26257
      - 8088:8080
    command: start-single-node --insecure
    volumes:
      - crdb_data:/cockroach/cockroach-data

  postgresql:
    image: postgres:14.7-alpine
    restart: always
    command: -c 'max_connections=200'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 7432:5432
    volumes:
      - postgresql:/var/lib/postgresql/data

  cube_api:
    restart: always
    image: cubejs/cube:latest
    ports:
      - 4008:4000
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_NAME: power_of_3_repo
      CUBEJS_DB_HOST: postgresql
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      ######
      #CUBEJS_DB_HOST: cockroach
      #CUBEJS_DB_USER: admin
      #CUBEJS_DB_PASS: admin
      #CUBEJS_DB_PORT: 26257
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: secret
      CUBEJS_DEV_MODE: "TRUE"
    volumes:
      - ./:/cube/conf
    depends_on:
      - cube_refresh_worker
      - cubestore_router
      - cubestore_worker_1
      - cubestore_worker_2

  cube_refresh_worker:
    restart: always
    image: cubejs/cube:latest
    environment:
      CUBEJS_DB_TYPE: postgres
      CUBEJS_DB_NAME: power_of_3_repo
      CUBEJS_DB_HOST: postgresql
      CUBEJS_DB_USER: postgres
      CUBEJS_DB_PASS: postgres
      ######
      #CUBEJS_DB_HOST: cockroach
      #CUBEJS_DB_USER: admin
      #CUBEJS_DB_PASS: admin
      #CUBEJS_DB_PORT: 26257
      CUBEJS_CUBESTORE_HOST: cubestore_router
      CUBEJS_API_SECRET: secret
      CUBEJS_REFRESH_WORKER: "TRUE"
    volumes:
      - ./:/cube/conf

  cubestore_router:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_PORT: 9999
      CUBESTORE_SERVER_NAME: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data

  cubestore_worker_1:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002
      CUBESTORE_SERVER_NAME: cubestore_worker_1:10001
      CUBESTORE_WORKER_PORT: 10001
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

  cubestore_worker_2:
    restart: always
    image: cubejs/cubestore:latest
    environment:
      CUBESTORE_WORKERS: cubestore_worker_1:10001,cubestore_worker_2:10002
      CUBESTORE_SERVER_NAME: cubestore_worker_2:10002
      CUBESTORE_WORKER_PORT: 10002
      CUBESTORE_REMOTE_DIR: /cube/data
      CUBESTORE_META_ADDR: cubestore_router:9999
    volumes:
      - .cubestore:/cube/data
    depends_on:
      - cubestore_router

volumes:
  postgresql:
  crdb_data:
